steps:
    - name: 'docker.io/library/python:3.7'
      id: INSTALL
      args:
        - 'pip install -r reuqirments.txt'
        
    - name: 'docker.io/library/python:3.7'
      id: RUN
      waitFor:
          - INSTALL
      args:
        - 'python3 practice1.py'