steps:
    - name: 'docker.io/library/python:3.7'
      id: INSTALL
    #   entrypoint: python3
      args:
        - 'pip install -r /workspace/reuqirments.txt'

    - name: 'docker.io/library/python:3.7'
      id: RUN
    #   entrypoint: python3
      waitFor:
          - INSTALL
      args:
        - 'python3 /workspace/practice1.py'