tags:
- "tensorflow_pg"
steps:
- id: "run code"
  name: 'docker.io/library/python:3.7'
  entrypoint: bash
  args:
    - '-c'
    - |
        pip install -r /workspace/requirements.txt\
        && python3 /workspace/practice1.py
options:
    machineType: 'N1_HIGHCPU_8'