steps:
    - name: 'docker.io/library/python:3.7'
      id: INSTALL
      entrypoint: bash
      args:
        - '-c'
        - |
            -m pip install -r /workspace/requirements.txt\
            && python3 /workspace/practice1.py